// Copyright (C) 2024 The Syncthing Authors.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at https://mozilla.org/MPL/2.0/.

//go:build ignore
// +build ignore

package main

// This program generates tables.go:
//	go run maketables.go -o tables.go

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"os"
	"strings"
	"text/template"
	"unicode/utf8"
)

// Copied from fat.go to avoid a circular dependency on tables.go
const (
	// BaseRune is the first rune in Unicode's Private Use Area plane.
	BaseRune = rune(0xf000)
	// NumChars is the range of characters we might encode (0-0xff).
	NumChars = 0x100 // 256
	// Encodes contains the characters the FAT encoder encodes.
	Encodes =
	/***/ "\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f" +
		"\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f" +
		`"*:<>?|` // \x22, \x2a, \x3a, \x3c, \x3e, \x3f, \x7c
	// Nevers contains characters we never encode.
	Nevers = "\x00/\\" // \x00, \x2f, \x5c
	// PatternNevers contains the characters we don't encode in glob patterns.
	PatternNevers = "*?" // \x2a, \x3f
)

var tpl = template.Must(template.New("fat").Parse("" +
	`// generated by go run maketables.go -o tables.go; DO NOT EDIT

// Copyright (C) 2024 The Syncthing Authors.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at https://mozilla.org/MPL/2.0/.

package fat

// puaEncodes contains the encoding table for the PUA encoder.
var puaEncodes = [NumChars]rune{
	{{.PUAEncodes}}
}

// puaPatternEncodes contains the encoding table for encoding glob patterns
// with the PUAPattern encoder.
var puaPatternEncodes = [NumChars]rune{
	{{.PUAPatternEncodes}}
}

`))

type templateVars struct {
	PUAEncodes        string
	PUAPatternEncodes string
}

func main() {
	outfile := flag.String("o", "", "Name of output file (default stdout)")
	flag.Parse()

	encodeMap := make(map[int]rune, NumChars)
	patternEncodeMap := make(map[int]rune, NumChars)

	for c := 0; c < NumChars; c++ {
		encodeMap[c] = rune(c)
		patternEncodeMap[c] = rune(c)
	}

	for _, r := range Encodes {
		if strings.ContainsRune(Nevers, r) {
			log.Fatalf("bug: the %q character cannot be encoded)", string(r))
		}
		if r < 0 || r >= NumChars {
			log.Fatalf("bug: the %q character cannot be encoded (as its Unicode "+
				"value (%d) is above %d)", string(r), r, NumChars-1)
		}

		c := int(r)
		encodeMap[c] = r | BaseRune

		if !strings.ContainsRune(PatternNevers, r) {
			patternEncodeMap[c] = r | BaseRune
		}
	}

	encodes := ""
	patternEncodes := ""
	for c := 0; c < NumChars; c++ {
		encodes += string(encodeMap[c])
	}
	for c := 0; c < NumChars; c++ {
		patternEncodes += string(patternEncodeMap[c])
	}

	var buf bytes.Buffer
	wrapAfter := 8
	tpl.Execute(&buf, templateVars{
		// Easier to read than fmt.Sprintf("%q", encodes).
		PUAEncodes:        wrappedRunes(encodes, wrapAfter),
		PUAPatternEncodes: wrappedRunes(patternEncodes, wrapAfter),
	})
	bs, err := format.Source(buf.Bytes())
	if err != nil {
		out := io.Writer(os.Stdout)
		out.Write(buf.Bytes())

		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	out := io.Writer(os.Stdout)
	if *outfile != "" {
		out, err = os.Create(*outfile)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
	out.Write(bs)
}

func wrappedRunes(input string, wrapAfter int) string {
	runes := utf8.RuneCountInString(input)
	wrapped := ""
	i := 0
	for _, r := range input {
		if i > 0 && i%wrapAfter == 0 {
			wrapped += "\n"
			if i < runes {
				wrapped += "\t"
			}
		}
		if i%wrapAfter != 0 {
			wrapped += " "
		}
		wrapped += fmt.Sprintf("'\\u%04x',", r)
		i++
	}
	return wrapped
}
