name: Build Syncthing (Nightly)

on:
  schedule:
    # Run nightly build at 05:00 UTC
    - cron: '00 05 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write

jobs:
  build-syncthing:
    uses: ./.github/workflows/build-syncthing.yaml
    if: contains(fromJSON('["syncthing", "calmh", "rasa"]'), repository_owner)
    secrets: inherit
