name: Build Syncthing (Nightly)

on:
  schedule:
    # Run nightly build at 15:00 UTC
    - cron: '00 15 * * *'

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write

jobs:
  build-syncthing:
    uses: ./.github/workflows/build-syncthing.yaml
    # if: contains(fromJSON('["syncthing", "calmh", "rasa"]'), repository_owner)
    secrets: inherit
