// Copyright (C) 2026 The Syncthing Authors.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at https://mozilla.org/MPL/2.0/.

//go:build ignore
// +build ignore

// Command maketables generates table.go via:
//
//	go run maketables.go -o table.go
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"os"
	"strings"
	"text/template"
	"unicode/utf8"

	"github.com/syncthing/syncthing/lib/encoder"
	"github.com/syncthing/syncthing/lib/encoder/rclone/consts"
)

var tpl = template.Must(template.New("rclone").Parse("" +
	`// generated by {{.CommandLine}}; DO NOT EDIT

// Copyright (C) 2026 The Syncthing Authors.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at https://mozilla.org/MPL/2.0/.

{{.BuildComments}}

package rclone

// rcloneEncodes contains the encoding table for the Rclone encoder.
var rcloneEncodes = [256]rune{
	{{.RcloneEncodes}}
}

// rclonePatternEncodes contains the encoding table for encoding glob patterns
// with the RclonePattern encoder.
var rclonePatternEncodes = [256]rune{
	{{.RclonePatternEncodes}}
}

`))

type templateVars struct {
	CommandLine          string
	BuildComments        string
	RcloneEncodes        string
	RclonePatternEncodes string
}

func main() {
	var outfile string
	flag.StringVar(&outfile, "o", "", "Name of output file (default stdout)")
	flag.Parse()

	rcloneEncodes := consts.Encodes

	encodeMap := make(map[int]rune, encoder.NumChars)
	patternEncodeMap := make(map[int]rune, encoder.NumChars)

	for c := 0; c < encoder.NumChars; c++ {
		encodeMap[c] = rune(c)
		patternEncodeMap[c] = rune(c)
	}

	for _, r := range rcloneEncodes {
		if strings.ContainsRune(encoder.Nevers, r) {
			log.Fatalf("bug: the %q character cannot be encoded)", string(r))
		}
		if r < 0 || r >= encoder.NumChars {
			log.Fatalf("bug: the %q character cannot be encoded (as its Unicode "+
				"value (%d) is above %d)", string(r), r, encoder.NumChars-1)
		}

		c := int(r)
		encodeMap[c] = consts.EncodeMap[r]

		if !strings.ContainsRune(encoder.PatternNevers, r) {
			patternEncodeMap[c] = consts.EncodeMap[r]
		}
	}

	encodes := ""
	patternEncodes := ""
	for c := 0; c < encoder.NumChars; c++ {
		encodes += string(encodeMap[c])
	}
	for c := 0; c < encoder.NumChars; c++ {
		patternEncodes += string(patternEncodeMap[c])
	}

	var buf bytes.Buffer
	wrapAfter := 8
	commandLine := "go run maketables.go -o table.go"

	tpl.Execute(&buf, templateVars{
		CommandLine: commandLine,
		// Easier to read than fmt.Sprintf("%q", encodes).
		RcloneEncodes:        wrappedRunes(encodes, wrapAfter),
		RclonePatternEncodes: wrappedRunes(patternEncodes, wrapAfter),
	})
	bs, err := format.Source(buf.Bytes())
	if err != nil {
		out := io.Writer(os.Stdout)
		out.Write(buf.Bytes())

		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	out := io.Writer(os.Stdout)
	if outfile != "" {
		out, err = os.Create(outfile)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
	out.Write(bs)
}

func wrappedRunes(input string, wrapAfter int) string {
	runes := utf8.RuneCountInString(input)
	wrapped := ""
	i := 0
	for _, r := range input {
		if i > 0 && i%wrapAfter == 0 {
			wrapped += "\n"
			if i < runes {
				wrapped += "\t"
			}
		}
		if i%wrapAfter != 0 {
			wrapped += " "
		}
		wrapped += fmt.Sprintf("'\\u%04x',", r)
		i++
	}
	return wrapped
}
